### ISSUE TITLE
Prepare release 0.12

### ISSUE THREAD

**Issue by pajoma** [pajoma/vscode-journal#114]
Milestone 1
- [x] disable codelens for now
- [x] keep codeactions for close task
- [x] implement codeaction for shift task 
- [x] remove markdown-it #102 
- [x] fix duplicate note links while syncing #97 
- [x] check why note links are not always injected while editor is open #97 
- [x] fix for placing items under correct heading
- [x] fix for #52 in release
- [x] serious refactoring to clean code base

**Comment by pajoma** [comment]
Milestone 2
- [ ] add telemetry
- [ ] check why syncing notes from scopes does not work
- [ ] add contributing.md #104

**Comment by pajoma** [comment]
Release as v 1.0.0
