### ISSUE TITLE
Tracking 0.5.0

### ISSUE THREAD

**Issue by pajoma** [pajoma/vscode-journal#12]
- [x] Improve startup times by lazy loading controller
- [x] Add notes reference after creating a new note
- [x] Edit Changelog
- [ ] Separate Wikipage for configuration options
- [ ] Pull open tasks of previous day by synchronizing (make that a feature to enable in config)
